import "./globals.scss";
import { Zen_Kaku_Gothic_Antique } from "@next/font/google";

const font = Zen_Kaku_Gothic_Antique({ weight: "400", subsets: ["japanese"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={font.className}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
